name: Deploy to Firebase project production

on:
  push:
    branches: [production]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: macos-latest 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install firebase-tools
        run: npm i -g firebase-tools
      - name: Create .env file
        run: echo "${{ secrets.ENV_PROD }}" > .env
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Deploy
        run: firebase deploy --project $FIREBASE_PROJECT_ID_PROD --token $FIREBASE_TOKEN
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_PROJECT_ID_PROD: ${{ secrets.FIREBASE_PROJECT_ID_PROD }}